USE DATABASE CAC_ANALYTICS;

-- ============================================================
-- TASK 1: Refresh deduplicated staging layer
-- ============================================================

CREATE OR REPLACE TASK ANALYTICS.TASK_REFRESH_CAC_STAGING
    WAREHOUSE = CAC_WH
    SCHEDULE = '1 HOUR'
    COMMENT = 'Refreshes the deduplicated CAC staging table from RAW data'
AS
CREATE OR REPLACE TABLE CAC_ANALYTICS.STAGING.CUSTOMER_ACQUISITION_STG AS
SELECT
    CUSTOMER_ID,
    MARKETING_CHANNEL,
    MARKETING_SPEND,
    NEW_CUSTOMERS,
    SOURCE_FILE_NAME,
    LOADED_AT
FROM CAC_ANALYTICS.RAW.CUSTOMER_ACQUISITION_RAW
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY CUSTOMER_ID
    ORDER BY LOADED_AT DESC
) = 1;


-- ============================================================
-- TASK 2: Refresh customer-level analytics
-- ============================================================

CREATE OR REPLACE TASK ANALYTICS.TASK_REFRESH_CAC_CUSTOMER_ANALYTICS
    WAREHOUSE = CAC_WH
    COMMENT = 'Refreshes customer-level CAC analytics from the deduplicated staging layer'
    AFTER ANALYTICS.TASK_REFRESH_CAC_STAGING
AS
CREATE OR REPLACE TABLE CAC_ANALYTICS.ANALYTICS.CAC_CUSTOMER_ANALYTICS AS
SELECT
    CUSTOMER_ID,
    MARKETING_CHANNEL,
    MARKETING_SPEND,
    NEW_CUSTOMERS,
    SOURCE_FILE_NAME,
    LOADED_AT,
    ROUND(
        MARKETING_SPEND / NULLIF(NEW_CUSTOMERS, 0),
        2
    ) AS CAC,
    ROUND(
        (NEW_CUSTOMERS / NULLIF(MARKETING_SPEND, 0)) * 100,
        4
    ) AS CONVERSION_RATE
FROM CAC_ANALYTICS.STAGING.CUSTOMER_ACQUISITION_STG;


-- ============================================================
-- TASK 3: Refresh channel-level summary
-- ============================================================

CREATE OR REPLACE TASK ANALYTICS.TASK_REFRESH_CAC_CHANNEL_SUMMARY
    WAREHOUSE = CAC_WH
    COMMENT = 'Refreshes channel-level CAC summary from customer analytics'
    AFTER ANALYTICS.TASK_REFRESH_CAC_CUSTOMER_ANALYTICS
AS
CREATE OR REPLACE TABLE CAC_ANALYTICS.ANALYTICS.CAC_CHANNEL_SUMMARY AS
SELECT
    MARKETING_CHANNEL,
    COUNT(*) AS CUSTOMER_COUNT,
    SUM(MARKETING_SPEND) AS TOTAL_MARKETING_SPEND,
    SUM(NEW_CUSTOMERS) AS TOTAL_NEW_CUSTOMERS,
    ROUND(
        AVG(CAC),
        2
    ) AS AVERAGE_CAC,
    ROUND(
        SUM(MARKETING_SPEND) / NULLIF(SUM(NEW_CUSTOMERS), 0),
        2
    ) AS WEIGHTED_CAC,
    ROUND(
        AVG(CONVERSION_RATE),
        4
    ) AS AVERAGE_CONVERSION_RATE
FROM CAC_ANALYTICS.ANALYTICS.CAC_CUSTOMER_ANALYTICS
GROUP BY MARKETING_CHANNEL
ORDER BY MARKETING_CHANNEL;


-- ============================================================
-- TASK 4: Refresh executive summary
-- ============================================================

CREATE OR REPLACE TASK ANALYTICS.TASK_REFRESH_CAC_EXECUTIVE_SUMMARY
    WAREHOUSE = CAC_WH
    COMMENT = 'Refreshes the executive CAC summary from channel-level analytics'
    AFTER ANALYTICS.TASK_REFRESH_CAC_CHANNEL_SUMMARY
AS
CREATE OR REPLACE TABLE CAC_ANALYTICS.ANALYTICS.CAC_EXECUTIVE_SUMMARY AS
SELECT
    COUNT(*) AS TOTAL_CUSTOMERS,
    SUM(MARKETING_SPEND) AS TOTAL_MARKETING_SPEND,
    SUM(NEW_CUSTOMERS) AS TOTAL_NEW_CUSTOMERS,
    ROUND(
        SUM(MARKETING_SPEND) / NULLIF(SUM(NEW_CUSTOMERS), 0),
        2
    ) AS OVERALL_WEIGHTED_CAC,
    ROUND(
        AVG(CAC),
        2
    ) AS OVERALL_AVERAGE_CAC,
    ROUND(
        AVG(CONVERSION_RATE),
        4
    ) AS OVERALL_AVERAGE_CONVERSION_RATE,
    COUNT(DISTINCT MARKETING_CHANNEL) AS MARKETING_CHANNEL_COUNT
FROM CAC_ANALYTICS.ANALYTICS.CAC_CUSTOMER_ANALYTICS;